### ISSUE TITLE
Add support for cancellable promise interface?

### ISSUE THREAD

**Issue by atesgoral** [atesgoral/pxy#2]
Consider adding support for @domenic's [cancelable-promise](https://github.com/domenic/cancelable-promise)

**Comment by domenic** [comment]
Don't use that; it's a brainstorming repo.

**Comment by atesgoral** [comment]
@domenic Emphasis on the "?" at the end of the issue title :) I created this issue as a brainstorming issue as well... Some standard around cross-library cancellable promises will be great. Anyway, I'll be watching where your things goes...
